---
name: Deploy production

on:
  workflow_dispatch:

jobs:

  1st:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo first step
  2nd:
    needs: 1st
    runs-on: ubuntu-latest
        steps:
          - run: |
              echo second step
