---
name: Must Succeed first Job

on:
  workflow_dispatch:

jobs:

  first:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo first step
  second:
    needs: second
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo second step
